### ISSUE TITLE
Handle extras_require

### ISSUE THREAD

**Issue by ZdenekM** [Arkq/flake8-requirements#27] opened 2020-08-26 10:44 UTC
I'm getting ```I900 'pytest' not listed as a requirement``` for test_something.py file importing pytest, even thought pytest is mentioned in setup.py:

```python
extras_require={
        'test': [
            'pytest'
]}
```

Is there something that can be done to make flake8-requirements happy? Or is it that it can't figure out the relation between test_*.py file and 'test' optional dependencies? Many thanks!

**Comment by Arkq** [comment] 2020-09-01 10:35
Hmm... flake8-requirements already checks for extras_require. I've checked
with a simple test project (setup.py and main.py in the same directory) and
dependencies from extras_require were not reported. Could you provide a
simple PoC where this is not working for you? If you are working on an
open-source project, simple point repo location.

**Comment by Arkq** [comment] 2021-03-27 19:49
Since I'm not able to reproduce this issue, I'm closing it. If it still occurs, please reopen it and provide more information (reproduction steps).

**Closed by Arkq** 2021-03-27 19:49 UTC
